all:
  children:
    k8s_cluster:
      children:
        master:
          hosts:
            k8s-master:
              ansible_host: "{{ master_ip }}"
        workers:
          hosts:
            k8s-worker1:
              ansible_host: "{{ worker1_ip }}"
            k8s-worker2:
              ansible_host: "{{ worker2_ip }}"
            k8s-worker3:
              ansible_host: "{{ worker3_ip }}"
            
  vars:
    ansible_user: sure
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_become: yes
    kubernetes_version: "1.29.*"  # 최신 버전으로 업데이트
    pod_network_cidr: "192.168.0.0/16"
    container_runtime: containerd
    nvidia_driver_version: "535"  # Ubuntu 24.04용 최신 안정 버전
    disable_swap: true
    timezone: "Asia/Seoul"
